name: CI test


on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x,20.x,22.x,23.x] 
    
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
      - name:
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version }}
      - name: Installing dependences
        run: npm ci
      - name: Running test
        run: npx vitest
        
